// Background themes: tint the page background and card/panel surfaces,
// independent of both the dark/light toggle (structural) and the accent
// color theme (buttons/links/focus rings — see themes.ts). Each theme
// defines both a light and dark variant in globals.css, so it composes
// with the existing dark-mode toggle rather than replacing it.
export interface BackgroundTheme {
  id: string;
  name: string;
  swatch: string;
}

export const BACKGROUND_THEMES: BackgroundTheme[] = [
  { id: "default", name: "Default", swatch: "hsl(0 0% 60%)" },
  { id: "cloud", name: "Cloud", swatch: "hsl(0 30% 55%)" },
  { id: "linen", name: "Linen", swatch: "hsl(40 30% 55%)" },
  { id: "porcelain", name: "Porcelain", swatch: "hsl(210 30% 55%)" },
  { id: "stone", name: "Stone", swatch: "hsl(30 30% 55%)" },
  { id: "ash", name: "Ash", swatch: "hsl(240 30% 55%)" },
  { id: "pearl", name: "Pearl", swatch: "hsl(200 30% 55%)" },
  { id: "bone", name: "Bone", swatch: "hsl(45 30% 55%)" },
  { id: "graphite", name: "Graphite", swatch: "hsl(220 30% 55%)" },
  { id: "ocean", name: "Ocean", swatch: "hsl(210 45% 55%)" },
  { id: "sky-wash", name: "Sky Wash", swatch: "hsl(200 40% 55%)" },
  { id: "denim", name: "Denim", swatch: "hsl(215 35% 55%)" },
  { id: "cobalt-mist", name: "Cobalt Mist", swatch: "hsl(220 50% 55%)" },
  { id: "arctic", name: "Arctic", swatch: "hsl(195 30% 55%)" },
  { id: "navy-night", name: "Navy Night", swatch: "hsl(225 40% 55%)" },
  { id: "steel-blue", name: "Steel Blue", swatch: "hsl(205 30% 55%)" },
  { id: "seafoam", name: "Seafoam", swatch: "hsl(170 35% 55%)" },
  { id: "aqua-mist", name: "Aqua Mist", swatch: "hsl(185 40% 55%)" },
  { id: "teal-dusk", name: "Teal Dusk", swatch: "hsl(175 30% 55%)" },
  { id: "glacier", name: "Glacier", swatch: "hsl(190 30% 55%)" },
  { id: "lagoon", name: "Lagoon", swatch: "hsl(180 45% 55%)" },
  { id: "turquoise-frost", name: "Turquoise Frost", swatch: "hsl(178 38% 55%)" },
  { id: "sage", name: "Sage", swatch: "hsl(100 30% 55%)" },
  { id: "moss", name: "Moss", swatch: "hsl(95 30% 55%)" },
  { id: "fern", name: "Fern", swatch: "hsl(110 35% 55%)" },
  { id: "eucalyptus", name: "Eucalyptus", swatch: "hsl(150 30% 55%)" },
  { id: "forest-night", name: "Forest Night", swatch: "hsl(140 35% 55%)" },
  { id: "mint-frost", name: "Mint Frost", swatch: "hsl(160 30% 55%)" },
  { id: "olive-grove", name: "Olive Grove", swatch: "hsl(75 30% 55%)" },
  { id: "jade", name: "Jade", swatch: "hsl(155 40% 55%)" },
  { id: "basil", name: "Basil", swatch: "hsl(105 30% 55%)" },
  { id: "pine", name: "Pine", swatch: "hsl(145 30% 55%)" },
  { id: "honeydew", name: "Honeydew", swatch: "hsl(90 30% 55%)" },
  { id: "lavender-haze", name: "Lavender Haze", swatch: "hsl(260 35% 55%)" },
  { id: "plum-dusk", name: "Plum Dusk", swatch: "hsl(280 35% 55%)" },
  { id: "aubergine", name: "Aubergine", swatch: "hsl(285 40% 55%)" },
  { id: "orchid-mist", name: "Orchid Mist", swatch: "hsl(300 30% 55%)" },
  { id: "indigo-night", name: "Indigo Night", swatch: "hsl(245 40% 55%)" },
  { id: "wisteria", name: "Wisteria", swatch: "hsl(265 30% 55%)" },
  { id: "amethyst", name: "Amethyst", swatch: "hsl(275 45% 55%)" },
  { id: "grape-mist", name: "Grape Mist", swatch: "hsl(290 35% 55%)" },
  { id: "heather", name: "Heather", swatch: "hsl(270 30% 55%)" },
  { id: "rose-quartz", name: "Rose Quartz", swatch: "hsl(340 30% 55%)" },
  { id: "blush", name: "Blush", swatch: "hsl(350 30% 55%)" },
  { id: "peony", name: "Peony", swatch: "hsl(330 35% 55%)" },
  { id: "cherry-blossom", name: "Cherry Blossom", swatch: "hsl(345 30% 55%)" },
  { id: "merlot", name: "Merlot", swatch: "hsl(355 40% 55%)" },
  { id: "berry-dusk", name: "Berry Dusk", swatch: "hsl(325 35% 55%)" },
  { id: "champagne", name: "Champagne", swatch: "hsl(45 30% 55%)" },
  { id: "golden-hour", name: "Golden Hour", swatch: "hsl(40 40% 55%)" },
  { id: "amber-glow", name: "Amber Glow", swatch: "hsl(35 45% 55%)" },
  { id: "terracotta", name: "Terracotta", swatch: "hsl(15 35% 55%)" },
  { id: "clay", name: "Clay", swatch: "hsl(20 30% 55%)" },
  { id: "caramel", name: "Caramel", swatch: "hsl(30 35% 55%)" },
  { id: "cocoa", name: "Cocoa", swatch: "hsl(25 30% 55%)" },
  { id: "espresso", name: "Espresso", swatch: "hsl(22 30% 55%)" },
  { id: "coral-wash", name: "Coral Wash", swatch: "hsl(8 40% 55%)" },
  { id: "vanilla-cream", name: "Vanilla Cream", swatch: "hsl(50 30% 55%)" },
  { id: "lemon-chiffon", name: "Lemon Chiffon", swatch: "hsl(55 30% 55%)" },
  { id: "butter", name: "Butter", swatch: "hsl(48 35% 55%)" },
  { id: "wine", name: "Wine", swatch: "hsl(0 40% 55%)" },
  { id: "crimson-dusk", name: "Crimson Dusk", swatch: "hsl(355 45% 55%)" },
  { id: "brick", name: "Brick", swatch: "hsl(10 30% 55%)" },
  { id: "rust", name: "Rust", swatch: "hsl(12 35% 55%)" },
  { id: "twilight", name: "Twilight", swatch: "hsl(230 30% 55%)" },
  { id: "nightfall", name: "Nightfall", swatch: "hsl(235 30% 55%)" },
  { id: "midnight", name: "Midnight", swatch: "hsl(225 30% 55%)" },
  { id: "storm", name: "Storm", swatch: "hsl(215 30% 55%)" },
  { id: "onyx", name: "Onyx", swatch: "hsl(260 30% 55%)" },
  { id: "ink", name: "Ink", swatch: "hsl(220 30% 55%)" },
  { id: "coal", name: "Coal", swatch: "hsl(20 30% 55%)" },
  { id: "smoke", name: "Smoke", swatch: "hsl(0 30% 55%)" },
  { id: "pewter", name: "Pewter", swatch: "hsl(210 30% 55%)" },
];
