import type { Metadata } from "next";
import Link from "next/link";
import StaticPage from "@/components/StaticPage";
import { SITE_URL, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms for using ${SITE_NAME}'s free AI tools.`,
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <StaticPage title="Terms of Service" subtitle="Last updated: July 31, 2026">
      <p>
        By using {SITE_NAME} (&ldquo;the site&rdquo;), you agree to the terms below. If you
        don&apos;t agree, please don&apos;t use the site.
      </p>

      <h2>The service</h2>
      <p>
        {SITE_NAME} provides free, AI-generated text suggestions (names, messages, drafts, and
        similar). A free account is required to generate results. The service is provided
        &ldquo;as is&rdquo; — we don&apos;t guarantee uninterrupted availability, and results may be
        rate-limited per tool to keep the service sustainable.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Every result on this site is generated by an AI language model, not a human. Outputs can be
        inaccurate, generic, or occasionally inappropriate. You&apos;re responsible for reviewing,
        fact-checking, and editing anything you use — especially names, legal or business content,
        and anything involving trademarks, availability, or claims about real people or products. We
        don&apos;t warrant that any generated name, phrase, or draft is free to use, original, or fit
        for a particular purpose.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Automate or script requests to bypass rate limits or scrape the site at scale.</li>
        <li>Use the site to generate content that is illegal, harassing, or defamatory.</li>
        <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the service.</li>
      </ul>

      <h2>Advertising and affiliate links</h2>
      <p>
        This site may display third-party ads (e.g. Google AdSense) and may include affiliate links
        to products or services. If you click an affiliate link and make a purchase, we may earn a
        commission at no extra cost to you. This doesn&apos;t affect the AI-generated results, which
        aren&apos;t influenced by any affiliate relationship.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, {SITE_NAME} and its operator aren&apos;t liable for
        any loss or damage arising from your use of, or inability to use, the site or its generated
        content.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms as the site changes. Continued use after an update means you
        accept the revised terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Reach out via the <Link href="/contact">contact page</Link>.
      </p>
    </StaticPage>
  );
}
